# Generated by Django 6.0.5 on 2026-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_historicalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details_doc',
            field=models.FileField(blank=True, help_text='Upload event details or agenda documents.', null=True, upload_to='event_details/'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='details_doc',
            field=models.TextField(blank=True, help_text='Upload event details or agenda documents.', max_length=100, null=True),
        ),
    ]
