# Generated by Django 6.0.5 on 2026-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_historicalfundpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_pdf',
            field=models.FileField(blank=True, help_text='PDF or document proving the expense.', null=True, upload_to='expenses/receipts/'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='receipt_pdf',
            field=models.TextField(blank=True, help_text='PDF or document proving the expense.', max_length=100, null=True),
        ),
    ]
